Jenkinsfile
=> modifying jenkins file for pipeline work

src/main/features/claim/views/start.njk, yarn.lock
=> add translation to start page

src/main/features/claim/views/housing-disrepair.njk, src/main/features/claim/views/personal-injury.njk, yarn.lock
=> show error message above radio options

Jenkinsfile
=> remove integration tests

src/main/server.ts
=> adding environment port

package.json, tsconfig.json, yarn.lock
=> Upgrade typescript, tslint and tsnode  versions

docker-compose.local.yml, docker-compose.yml
docker compose file changes for setup
=> Integration test setup 

Jenkinsfile
=> giving consistent resource name on jenkins file

config/custom-environment-variables.json, config/default.json, src/test/features/claim/routes/checks/authorization-check.ts, src/test/features/claim/routes/claimant-address.ts, src/test/features/claim/routes/defendant-address.ts, src/test/features/claim/routes/defendant-represented.ts, src/test/features/claim/routes/defendant-reps-address.ts, src/test/features/claim/routes/defendnt-details.ts, src/test/features/claim/routes/housing-disrepair.ts, src/test/features/claim/routes/personal-injury.ts, src/test/features/claim/routes/preferred-court.ts, src/test/features/claim/routes/receiver.ts, src/test/features/claim/routes/representative-address.ts, src/test/features/claim/routes/representative-contacts.ts, src/test/features/claim/routes/representative-name.ts, src/test/features/claim/routes/start.ts, src/test/features/claim/routes/summarise-the-claim.ts, src/test/features/claim/routes/your-reference.ts
=> Update to use https

src/main/app/forms/models/address.ts, src/main/features/claim/routes/claimant-address.ts, src/main/features/claim/routes/defendant-address.ts, src/main/features/claim/routes/defendant-reps-address.ts, src/test/app/forms/models/address.ts
=> ROC-1776: Action sign off comments

src/main/app/forms/models/contactDetails.ts, src/main/features/claim/views/representative-contacts.njk, src/test/app/forms/models/contactDetails.ts
Sign-off feedback:
1. Change text to indicate to the defendant that they can contact the claimant legal rep using these details
2. Tag all fields as optional
3. Make all fields optional
4. Use the validation messages from the spreadsheet attached to this Jira issue
=> Implement sign off comments

Jenkinsfile, config/custom-environment-variables.json
=> added new variable and removed unused services

Jenkinsfile
=> adding changes after review

package.json, src/main/features/claim/views/housing-disrepair.njk, src/main/features/claim/views/personal-injury.njk, src/main/features/claim/views/summarise-the-claim.njk, yarn.lock
fix error line problem and remove text
=> ROC-1784 - Select Claim track

package.json, src/main/features/claim/views/summarise-the-claim.njk, src/main/public/stylesheets/components/_form.scss, yarn.lock
changed the class on summarise the claim page
=> ROC-1786 summarise the claim

src/main/features/claim/views/defendant-represented.njk, src/test/features/claim/routes/defendant-represented.ts
**Jira:**
https://tools.hmcts.net/jira/browse/ROC-2092
**Description:**
The question should read: "Has the defendant got a representative who's instructed to accept service?"
=> Update heading text

Jenkinsfile
=> ROC-1814: uncommenting integration tests

Jenkinsfile
=> ROC-1814: Integration test not ready

src/main/app/forms/models/feeAccount.ts, src/main/app/forms/validation/validators/isFeeAccount.ts, src/test/app/forms/validation/validators/isFeeAccountConstraint.ts, src/test/features/claim/routes/pay-by-account.ts
Jira:
https://tools.hmcts.net/jira/browse/ROC-1794
Implemented new A/C: 
`4. Allow leading and trailing spaces`
=> Allow leading and trailing spaces for fee account no

src/main/app/utils/numberFormatter.ts, src/test/app/utils/numberFormatter.ts
**Jira:**
https://tools.hmcts.net/jira/browse/ROC-1788
**Description:**
Does not show decimal places if only .00/whole number for feeAmount and claimValue.
=> Display decimals in money only if present

src/main/features/claim/views/total.njk
Jira:
https://tools.hmcts.net/jira/browse/ROC-2154
=> Static text update

src/main/features/claim/views/personal-injury.njk
Fix wording on Personal Injury question
=> ROC-2173: Update static text for personal Injury

Jenkinsfile
=> Update jenkin file to generate html report

src/main/features/claim/views/housing-disrepair.njk
=> Housing disrepair content

package.json, yarn.lock
This PR uses the updated macro from common-frontend, which increases the width of middle column to be on half and others to be one quarter.
=> Increase width of middle column

src/main/features/claim/views/details-summary.njk
This PR corrects the wordings for statement of value. i.e making use of correct variable.
=> Fix statement of value issue

src/main/app/claims/claimModelConverter.ts
Reverts hmcts/cmc-legal-rep-frontend#99
=> Revert "Update Amount Type in front end"

Jenkinsfile
=> put demo deploy step in

src/main/app/claims/claimModelConverter.ts
Reverts hmcts/cmc-legal-rep-frontend#107
=> move preferred court and external reference number to draftClaim

src/main/features/claim/views/submitted.njk
=> add in new content for claim submitted

src/main/app/drafts/models/draftLegalClaim.ts, src/main/app/fees/fee.ts, src/main/app/fees/feesClient.ts, src/main/features/claim/routes/details-summary.ts, src/main/features/claim/routes/pay-by-account.ts, src/main/features/claim/routes/total.ts, src/test/http-mocks/fees.ts
Jira:
https://tools.hmcts.net/jira/browse/ROC-2273
This PR adds fee code to be stored in claim. Claim Store PR for the same is: https://git.reform.hmcts.net/cmc/claim-store/pull/156
=> Persist x code from Fees Register API call

src/main/app/claims/claimModelConverter.ts
This PR sends companies house number to claim store for persistence.
=> Persist companies house no in claim store

src/main/app/forms/models/amount.ts
This PR updated the error message contents.
=> Update error message content

package.json
=> Removing alpha from version

src/main/features/claim/routes/defendant-add.ts
This PR updated the maximum defendant's limit.
=> Update defendants limit

src/main/routes/health.ts
=> adding missing claim-store Health check

src/main/routes/health.ts
=> adding pdf-service HC

src/test/app/utils/momentFormatter.ts, src/test/app/utils/stringUtils.ts
This PR adds missing unit tests for `MomentFormatter` and `StringUtils`.
=> Add missing unit tests

.travis.yml, README.md, package.json, sonar-project.properties, yarn.lock
=> ROC-2300: Add sonar properties

src/main/app/forms/models/address.ts, src/main/features/claim/views/representative-contacts.njk, src/main/features/claim/views/start.njk, src/main/features/claim/views/statement-of-truth.njk, src/main/features/claim/views/submitted.njk
=> Ronan content sweep

package.json
This PR updated the sonar property to be used.
=> Update sonar property

package.json, yarn.lock
update version to new common-frontend
=> ROC-2410 - Briefly-desribe-whitespace 

src/main/features/claim/views/pay-by-account.njk
=> BUG: Pay and Issue update to use correct macro

src/main/features/claim/views/pay-by-account.njk, src/main/public/js/jquery-prevent-double-submit.js, src/main/views/includes/scripts.njk
This PR adds guard to prevent double/multiple submissions of a claim. This is non breaking change.
=> Prevent double submit of pay and issue

src/main/app/claims/claimStoreClient.ts, src/main/app/claims/searchClaim.ts, src/test/app/claims/searchClaim.ts
This PR adds the clients to utilise search by reference and search by external references from claim-store.
=> ROC-2513: Feature/roc 2513 search for single claim api call

package.json, src/main/app/fees/fee.ts, src/main/app/fees/feesClient.ts, src/main/app/fees/model/fee.ts, src/main/app/fees/model/feeResponse.ts, src/main/features/claim/routes/details-summary.ts, src/main/features/claim/routes/pay-by-account.ts, src/main/features/claim/routes/total.ts, yarn.lock
This PR utilises new endpoint for fees-api for unspecified claim value.
=> Update fees-api endpoint for unspecified claim value

src/main/app/forms/models/amount.ts, src/main/features/claim/views/amount.njk, src/main/features/claim/views/start.njk
=> Ronan content 2510

Jenkinsfile
https://tools.hmcts.net/jira/browse/ROC-2432
=> ROC-2432: Run only legal frontend integration tests on builds

src/main/features/dashboard/views/claim-details.njk, src/main/public/stylesheets/components/_form.scss
=> ROC-2521 Design tweeks

Jenkinsfile
=> enable routes stage in Jenkins

src/main/modules/helmet/modules/contentSecurityPolicy.ts
* fix medium security scanner error
=> fix medium security scanner error

src/main/app/forms/models/serviceAddress.ts, src/main/features/claim/views/claimant-type.njk, src/main/features/claim/views/defendant-type.njk, src/test/features/claim/routes/amount.ts, src/test/features/claim/routes/claimant-add.ts, src/test/features/claim/routes/claimant-address.ts, src/test/features/claim/routes/claimant-type.ts, src/test/features/claim/routes/defendant-add.ts, src/test/features/claim/routes/defendant-address.ts, src/test/features/claim/routes/defendant-represented.ts, src/test/features/claim/routes/defendant-reps-address.ts, src/test/features/claim/routes/defendant-service-address.ts, src/test/features/claim/routes/defendant-type.ts, src/test/features/claim/routes/housing-disrepair.ts, src/test/features/claim/routes/pay-by-account.ts, src/test/features/claim/routes/personal-injury.ts, src/test/features/claim/routes/representative-address.ts, src/test/features/claim/routes/statement-of-truth.ts, src/test/features/claim/routes/summarise-the-claim.ts, src/test/features/dashboard/routes/claim-details.ts, src/test/features/dashboard/routes/search.ts, src/test/http-mocks/claim-store.ts
https://tools.hmcts.net/jira/browse/ROC-2777
=> ROC-2776 Update route tests

src/main/app/forms/models/search.ts
https://tools.hmcts.net/jira/browse/ROC-2809
=> ROC-2809 apply upper case to the search reference given

src/main/public/stylesheets/components/_form.scss
https://tools.hmcts.net/jira/browse/ROC-2809
=> ROC-2809 put outline inside the input

config/custom-environment-variables.json, config/default.json, src/main/modules/nunjucks/index.ts, src/main/views/includes/phase_banner_beta.njk, src/main/views/includes/support-links.njk
https://tools.hmcts.net/jira/browse/ROC-2149
=> ROC-2149 Add in links to survey monkey for report a problem and feedback

src/main/app/documents/documentsClient.ts, src/main/features/claim/routes/receipt.ts, src/test/app/documents/documentsClient.ts
=> ROC-2520 Retrieve sealed claim

package.json, src/main/routes/health.ts, src/main/routes/info.ts, yarn.lock
Note that document management web doesn't provide an info endpoint yet,
so haven't added them. Will ask them if they will add it though.
=> ROC-2459 Add info provider library

src/main/public/stylesheets/components/_document-upload.scss
https://tools.hmcts.net/jira/browse/ROC-2911
=> Add in word wrapping for file names

Jenkinsfile
=> cmc legal rep jenkins build data to influx

package.json, src/main/common/router/defendants.ts, src/main/public/stylesheets/components/_form.scss, yarn.lock
Add in missing css and sole trade name for party stripe
=> ROC-2719 Add Sole Trader as defendant

src/main/app.ts, src/main/app/claims/claimStoreClient.ts, src/main/features/claim/routes/pay-by-account.ts, src/main/features/claim/routes/receipt.ts, src/main/features/claim/routes/submitted.ts
This PR adds auth token to claim store client. 
**Jira:**
[ROC-3020](https://tools.hmcts.net/jira/browse/ROC-3020)
=> ROC-3020: Add auth token to claim store calls

package.json, yarn.lock
=> fix(package): update tsconfig-paths to version 3.1.1

package.json, src/main/app/forms/models/amount.ts, yarn.lock
=> fix(package): update class-validator to version 0.8.1

Dockerfile, integration-tests.Dockerfile, saucelabs.conf.js
- reorder integration tests `Dockerfile` statements to save time,
- quote `Dockerfile` proxy values to avoid connectivity issues on local environments,
- trim unwanted whitespace from configuration values.
=> Codecept related improvements

package.json, src/main/app.ts, src/main/app/paths.ts, src/main/app/utils/momentFormatter.ts, src/main/features/claim/routes/submitted.ts, src/main/features/claim/views/submitted.njk, src/main/modules/i18n/backend.ts, src/main/modules/i18n/index.ts, src/main/modules/nunjucks/filters/dateFilter.ts, src/main/modules/nunjucks/index.ts, src/main/routes/analytics.ts, src/test/app/utils/momentFormatter.ts, src/test/common/utils/uuidUtils.ts, src/test/features/claim/routes/submitted.ts, src/test/modules/i18n/backend.ts, src/test/modules/i18n/fixtures/translation.po, src/test/modules/nunjucks/filters/convertToPounds.ts, src/test/modules/nunjucks/filters/dateFilter.ts, src/test/routes/analytics.ts
Also made the date format consistent with T1 see ROC-2299
=> Improve test coverage... and exclude some things from being checked as they pass straight off into libraries and testing would provide no value

package.json, yarn.lock
=> fix(package): update i18next to version 11.1.1

package.json, yarn.lock
=> chore(package): update gulp-sass to version 4.0.1

infrastructure/main.tf
This PR adds missing claim-store config for preview env.
=> Add claim store configs for preview

src/integration-test/tests/legal/amountClaim/pages/submitted.js
This PR fixes the flaky assertion in functional tests.
=> Fix flaky assertion

src/main/modules/helmet/modules/contentSecurityPolicy.ts
=> Update content security policy for new inline code

src/main/routes/receiver.ts
Same change as https://github.com/hmcts/cmc-citizen-frontend/pull/612
JIRA: https://tools.hmcts.net/jira/browse/ROC-3573
=> ROC-3573: Track state cookie mismatch event instead of throwing error

Jenkinsfile_CNP, Jenkinsfile_parameterized, infrastructure/main.tf, infrastructure/output.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/ROC-3940
Use azure key vault for secrets instead of hashi vault
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
=> ROC-3940 Use azure key vault for secrets

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/ROC-3940
Now that the hashi secrets are removed from the state the provider can be removed
=> ROC-3940 Remove hashi vault provider

src/main/features/dashboard/views/claim-details.njk, src/main/features/dashboard/views/search.njk, src/main/public/stylesheets/components/_layout.scss
Hack it so that blue bars line up, not sure if needed but UX wanted it
and add trading as for sole traders
=> ROC-3832 Small improvements

src/integration-test/helpers/clients/idamClient.ts
Add back in /legal because of idam whitelisting
=> [PREVIEW] Fix test

package.json, yarn.lock
=> Greenkeeper/i18next 12.1.0

package.json, yarn.lock
=> Greenkeeper/husky 1.2.0

package.json, yarn.lock
=> Greenkeeper/i18next conv 8.0.1

Dockerfile
Resolves [CNP-1109](https://tools.hmcts.net/jira/browse/CNP-1109)
Hello, this PR adds the following enhancements:
- improve the ordering of the docker image build layer 
- prepare for future ACR cache optimisations.
This is part of a general [pipelines optimisations initiative](https://tools.hmcts.net/confluence/display/CNP/Pipeline+optimisations) and should not impact the current builds.
=> Optimise docker image build layers

infrastructure/prod.tfvars
Updating prod config to correct idam api url.
=> Prod issue - fix idam auth issue

.dockerignore, .gitignore, Dockerfile, acb.tpl.yaml
This PR leverages on layers re-use to reduce the the docker image build time in CI.
Jira ticket: https://tools.hmcts.net/jira/browse/CNP-1131
The PR CI shows a decrease of build time of the docker image.
=> Activate ACR build, image multistaging and hmcts runtime user

docker-compose.local.yml, docker-compose.yml
Fix image to match integration-tests.
=> Update docker-compose image to match integration-tests

Jenkinsfile_nightly, security.sh
=> set up cmc legal rep security scan

src/main/features/dashboard/views/claim-details.njk
Change title of claim details page
=> Change title of claim details page

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/ROC-4146
Missing a closing `}` - also fixed formating.
=> Fix nightly Jenkins security scanning

Jenkinsfile_CNP
Successfully tested on claim-store.
=> Fix git push to demo

Dockerfile
=> Fix user permissions on docker build

security.sh
=> set up cmc legal rep frontend false positive fix

Jenkinsfile_parameterized
Update jenkins files with new secrets format
=> Update jenkins files with new secrets format

charts/cmc-legal-frontend/Chart.yaml, charts/cmc-legal-frontend/requirements.yaml, charts/cmc-legal-frontend/values.aat.template.yaml, charts/cmc-legal-frontend/values.preview.template.yaml, charts/cmc-legal-frontend/values.yaml
tools.hmcts.net/jira/browse/ROC-5418
Helm changes required from RPE and some variable cleanup.
=> ROC-5418: Helm config changes

charts/cmc-legal-frontend/Chart.yaml, infrastructure/demo.tfvars, infrastructure/saat.tfvars
Update demo to SIDAM to bring in-line with AAT and Production.
Note: also includes a comment in Helm chart manifest 😊
=> Point to SIDAM (demo/saat)

charts/cmc-legal-frontend/values.yaml
Applying: https://github.com/hmcts/cmc-citizen-frontend/pull/1652
=> Remove default cpu limits

config/default.json, src/main/app/claims/models/claim.ts, src/main/app/pay/payClient.ts, src/main/features/claim/routes/pay-by-account.ts, src/test/features/claim/routes/pay-by-account.ts, src/test/http-mocks/pay.ts
=> ROC-5724: Update ccd case is in payment hub

Dockerfile
Update Docker image to use hmctspublic.
=> Update Docker base image hmcts public

acb.tpl.yaml, charts/cmc-legal-frontend/Chart.yaml, charts/cmc-legal-frontend/values.yaml, docker-compose.yml
RPE driven requirement to use hmctspublic ACR repo.
=> Update to use hmctspublic

acb.tpl.yaml, docker-compose.functional-tests.yml, docker-compose.local.yml, docker-compose.smoke-tests.yml, docker-compose.yml, integration-tests.Dockerfile
Use hmctspublic for integration tests image.
Already done for Citizen frontend.
=> Use hmctspublic for integration tests image

charts/cmc-legal-frontend/Chart.yaml, charts/cmc-legal-frontend/requirements.yaml, charts/cmc-legal-frontend/values.preview.template.yaml, infrastructure/main.tf, src/integration-test/bootstrap/bootstrap.ts, src/integration-test/helpers/clients/idamClient.ts
Update to use latest terraform infrastructure module
=> update infra module

charts/cmc-legal-frontend/values.yaml, config/custom-environment-variables.json, config/default.json, config/dockertests.json, infrastructure/main.tf, infrastructure/variables.tf, src/main/app/claims/claimStoreClient.ts
This PR implements inversion of Control for legal representatives frontend.
[ROC-6130](https://tools.hmcts.net/jira/browse/ROC-6130)
=> ROC-6130: Inversion of Control for legal representatives frontend

infrastructure/prod.tfvars, src/main/app/paths.ts, src/main/routes/accessibility-statement.ts, src/main/views/accessibility-statement.njk, src/main/views/includes/support-links.njk, src/test/routes/acessibility-statement.ts
=> Added new accessibility statement page

infrastructure/ithc.tfvars
This PR enables IOC for legal rep on ITHC env
=> Enable ioc on ithc

infrastructure/ithc.tfvars
=>  Update external host for ithc

infrastructure/aat.tfvars, infrastructure/ithc.tfvars
This PR turns IOC on for legal rep on AAT environment.
=> ROC-6132: Turn IOC on for legal rep on AAT

src/main/app/forms/models/search.ts, src/test/features/dashboard/routes/search.ts
https://tools.hmcts.net/jira/browse/ROC-6766
=> ROC-6766 Allow whitespace around a search reference

renovate.json
=> Renovate Update default config

src/main/app/forms/models/whatDocuments.ts
=> Fix sonar issue

package.json, yarn.lock
=> Fiddle with dependencies

Jenkinsfile_CNP
=> Switch to AKS on prod

src/main/modules/helmet/index.ts
https://tools.hmcts.net/jira/browse/ROC-7648
Add helmet configuration not to cache dynamic pages
**Does this PR introduce a breaking change?** (check one with "x")
=> ROC-7648 Do not cache dynamic files

infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
Notes:
*
* to decommission ASE AAT resources
*
https://tools.hmcts.net/jira/browse/ROC-7655
=> decommission ase aat

infrastructure/demo.tfvars, infrastructure/prod.tfvars, infrastructure/saat.tfvars, infrastructure/sprod.tfvars
Notes:
Jira Ticket:  https://tools.hmcts.net/jira/browse/ROC-7655
Description: decommission ASE PROD
=> decommission ase prod

infrastructure/state.tf
remove core-infra-apps
- [x ] No
=> remove core-infras

charts/cmc-legal-frontend/Chart.yaml, charts/cmc-legal-frontend/requirements.yaml
upgrade nodejs chart version
- [ x] No
=> upgrade nodejs chart version

src/main/features/claim/views/statement-of-truth.njk
https://tools.hmcts.net/jira/browse/ROC-7857
Statement of Truth changes for legal reason.
=> ROC-7857-SOT change for Legal Rep Journey

Jenkinsfile_CNP, docker-compose.yml
update jenkins and docker-compose files
- [ x] No
=> update config for jenkins

Jenkinsfile_CNP
remove deprecated jenkins function 
- [x ] No
=> remove deprecate jenkins function

docker-compose.functional-tests.yml, package.json
=> fix release pipeline

audit.json
=> updated audit json

audit.json
=> Security scan fix

src/integration-test/data/legal-test-data.ts, src/test/app/forms/models/feeAccount.ts, src/test/app/utils/cookies.ts, src/test/features/claim/routes/pay-by-account.ts
NA
Updated the latest test data.
=> Updated new PBA number

src/integration-test/tests/legal/home/steps/user.ts
NA
Fix for reference number test failure
=> Reference number

src/integration-test/tests/legal/amountClaim/enterAmountClaimDetails_test.ts
=> Test case failure fix

audit.json
=> updated audit.json

src/main/app/pay/model/paymentResponse.ts, src/test/http-mocks/pay.ts
> NA - It's servicenow ticket (INC5124636).
> Fix for the payment failure in legal rep application (Production live incident issue).
=> Bug fix : Payment failure 

Jenkinsfile_nightly, default.conf.js, package.json, saucelabs.conf.js, src/integration-test/bootstrap/bootstrap.ts, src/integration-test/crossbrowser/supportedBrowsers.js, src/integration-test/helpers/idamHelper.ts, src/integration-test/helpers/saucelabsReporter.js, src/integration-test/tests/legal/amountClaim/enterAmountClaimDetails_test.ts, types/steps.d.ts, yarn.lock
https://tools.hmcts.net/jira/browse/TA-378
https://tools.hmcts.net/jira/browse/TA-379
https://tools.hmcts.net/jira/browse/TA-380
https://tools.hmcts.net/jira/browse/TA-381
Update crossbrowser e2e test config and dependencies to run tagged tests nightly on chrome, including:
- Upgrade e2e dependencies to latest stable versions
- Refactor saucelabs.conf.js to W3C standard for webdriver capabilities
- Add latest browser list to cmc-citizen-frontend
- Configure with Jenkins nightly parallel pipeline compatibility
- Test reports, logs and screenshots / videos are visible in Jenkins (mochawsome / Saucelabs)
=> TA-378 & TA-379 & TA-380 & TA-381: Upgrade crossbrowser dependencies, config, and supported browsers list

src/integration-test/tests/legal/amountClaim/enterAmountClaimDetails_smoke_test.ts
https://tools.hmcts.net/jira/browse/TA-382
Allow @smoke-test tagged e2e test to retry up to 2 times, for benefit of the nightly crossbrowser pipeline where the risk of network or environmental flakiness causing false negatives (i.e. breaking the build) is higher.
Nightly pipeline passes:
=> TA-382: Add retries to @smoke-test tagged e2e test

config/default.json, src/main/app/pay/payClient.ts, yarn.lock
sending Case Type (case_type) as a mandatory field in the Payment request instead of the Site ID
https://tools.hmcts.net/jira/browse/ROC-8844
=> Start sending Case Type instead of Site ID

Jenkinsfile_CNP
=> env sync up

bin/run-crossbrowser-tests.sh, package.json
=> update cb tests

charts/cmc-legal-frontend/Chart.yaml, package.json, yarn.lock
=> update dependencies to fix build 
